version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A jobs.video_tasks worker --loglevel=info
    depends_on:
      - redis
